# Generated by Django 3.2.4 on 2021-06-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('carnumber', models.CharField(max_length=13)),
                ('phone', models.CharField(max_length=13)),
                ('date', models.DateField()),
            ],
        ),
    ]
